# DC SCHEMA

# --- !Ups


CREATE TABLE TEMPERATURE (
  ID          INTEGER          NOT NULL AUTO_INCREMENT PRIMARY KEY,
  TIMESTAMP   TIMESTAMP        NOT NULL,
  TEMPERATURE DOUBLE PRECISION NOT NULL
);


# --- !Downs

DROP TABLE TEMPERATURE;
